import Farcaster from "@/lib/farcaster"
import Providers from "@/lib/providers"
import type { Metadata } from "next"
import { Karla, Mogra } from "next/font/google"
import Image from "next/image"
import { ReactNode } from "react"
import "./globals.css"

const karla = Karla({
  variable: "--karla",
  weight: "variable",
  subsets: ["latin"],
})

const mogra = Mogra({
  variable: "--mogra",
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const { HOST } = process.env

const frame = {
  version: "next",
  imageUrl: `https://${HOST}/manifest/heroImage.png`,
  button: {
    title: "gift",
    action: {
      type: "launch_frame",
      url: `https://${HOST}`,
      name: "Monad Flowers",
      splashImageUrl: `https://${HOST}/manifest/splashImage.png`,
      splashBackgroundColor: "#ffffff",
    },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="fc:frame" content={JSON.stringify(frame)} />
      </head>
      <body className={`${karla.variable} ${mogra.variable} antialiased`}>
        <Providers>
          <Farcaster>{children}</Farcaster>
        </Providers>

        <div className="fixed -right-2 top-23 w-22.5 h-48 z-10 blur-[1px] pointer-events-none">
          <Image src={"/images/roses.png"} sizes="90px" fill alt="roses" />
        </div>
        <div className="fixed left-0 top-70 min-[370px]:top-77 w-28 h-57 z-10 blur-[1px] pointer-events-none">
          <Image src={"/images/violets.png"} sizes="112px" fill alt="violets" />
        </div>
        <div className="fixed right-0 bottom-0 w-23 h-23 z-10 blur-[1px] pointer-events-none">
          <Image src={"/images/blue-flower.png"} sizes="92px" fill alt="blue-flower" />
        </div>

        {["rose", "daisy", "lily", "sunflower", "tulip"].map(f => (
          <Image key={f} src={`/images/flowers/${f}.png`} sizes="144px" fill priority alt={f} className="hidden" />
        ))}
      </body>
    </html>
  )
}
